socket:
	gcc -o P1-socket P1-socket.c
	gcc -o P2-socket P2-socket.c
	./P1-socket


fifo:
	gcc -o P1-fifo P1-fifo.c
	gcc -o P2-fifo P2-fifo.c
	./P1-fifo


queue:
	gcc -o P1-queue P1-queue.c
	gcc -o P2-queue P2-queue.c
	./P1-queue